C = {
"lang": "en",
"file": "Guide-Investing-Dominican-Republic-2026-EN.pdf",
"cover_kicker": "Legal guide for foreign investors",
"cover_title": "Investing in the Dominican Republic",
"cover_year": "2026 Edition",
"cover_sub": "What to know and verify before you invest, so your assets in the Dominican Republic are protected from the very first signature.",
"since": "Since 2009",
"footer": "Cabinet Legal · Guide to Investing in the Dominican Republic 2026",

"letter_kicker": "A letter from the partners",
"letter_title": "A safe investment starts before you sign",
"letter": [
"The Dominican Republic is enjoying the strongest period in its history as an investment destination. Every year more buyers, entrepreneurs and retirees discover a combination that is hard to find elsewhere: sustained growth, openness to foreign capital and an exceptional quality of life.",
"Experience has also taught us that the problems in an investment rarely appear on the day of the purchase. They surface years later, when a title carried a lien nobody checked, when a development lacked its full permits, or when a company was set up with a structure that did not match the investor's plans.",
"We prepared this guide so you can approach every decision with the right information. It does not replace advice on your specific situation, but it will help you ask the right questions and spot the warning signs in time.",
],
"sign": "Aileen Espinosa and Ellis Beato",
"sign_role": "Partners, Cabinet Legal",
"toc_title": "Contents",
"toc": ["Why the Dominican Republic", "Legal framework for foreign investors", "Buying property step by step", "Purchase costs and taxes", "CONFOTUR incentives", "Setting up a company", "Residency by investment", "Mistakes to avoid", "Why Cabinet Legal"],

"why_kicker": "01 · Context",
"why_title": "Why the Dominican Republic",
"why_intro": "The Dominican economy has been one of the fastest growing in Latin America over the past two decades. In 2025 the country set new records in both foreign investment and tourism, the two engines behind real estate demand.",
"stats": [
["US$5.03 B", "in foreign direct investment in 2025, the highest in the country's history"],
["+11.3%", "growth in foreign investment compared with 2024"],
["11.68 M", "visitors in 2025, also an all-time record"],
["15.7%", "of 2025 foreign investment went into real estate"],
],
"stats_source": "Sources: Central Bank of the Dominican Republic (FDI 2025) and Ministry of Tourism (2025 arrivals).",
"why_points_title": "Advantages for investors",
"why_points": [
["Equal treatment", "Law 16-95 grants foreign investors the same rights as Dominican nationals and guarantees the free repatriation of capital and profits."],
["No ownership restrictions", "Foreigners may buy property in their own name or through a company, with no residency requirement and no need for a Dominican partner."],
["Registered titles", "The system created by Real Estate Registry Law 108-05 backs ownership with a Certificate of Title issued by the State."],
["Tax incentives", "Tourism projects classified under CONFOTUR offer exemptions that can make an investment considerably more profitable."],
],
"sectors_title": "Where foreign investment went in 2025",
"sectors": [["Tourism", 26.3], ["Energy", 23.8], ["Real estate", 15.7], ["Trade and industry", 10.5], ["Free trade zones", 8.7], ["Mining", 6.7], ["Other", 8.3]],

"legal_kicker": "02 · Legal framework",
"legal_title": "The laws that protect your investment",
"legal_intro": "Understanding the legal framework tells you what rights you have, what obligations you take on and which documents you should require in every transaction.",
"laws": [
["Law 16-95", "Foreign investment", "Guarantees equal treatment and the free remittance of capital and profits. Registering the investment with ProDominicana is the basis for applying for investor residency."],
["Law 108-05", "Real Estate Registry", "Governs the Certificate of Title, surveys (deslindes) and the registration of rights. Anything not recorded at the Title Registry cannot be enforced against third parties."],
["Law 479-08", "Commercial companies", "Sets out the corporate forms (SRL, SA, SAS, EIRL), their capital requirements, management bodies and registration duties."],
["Law 189-11", "Mortgage market and trusts", "Allows off-plan purchases through trusts that keep buyers' funds separate from the developer's own assets."],
["Law 158-01", "Tourism development (CONFOTUR)", "Amended by Law 195-13. Grants tax exemptions to classified tourism projects and their first buyers."],
["Law 171-07", "Retirees and rentiers", "Offers immigration and tax benefits to foreigners who show stable income or pensions from abroad."],
],
"legal_note": "A practical warning: in the Dominican Republic, physical possession of a property is no substitute for title. Always check the legal status at the Title Registry before paying.",

"buy_kicker": "03 · Buying property",
"buy_title": "Buying property step by step",
"buy_intro": "The process is safe when each step is carried out in the right order and with complete documentation. These are the stages of a well-structured purchase.",
"steps": [
["Offer and reservation", "The price is agreed and a reservation agreement is signed. Before handing over money, confirm who the registered owner is and on what terms the deposit will be refunded."],
["Due diligence", "Review of the Certificate of Title, legal status certificate, liens and encumbrances, survey and cadastral plan, property taxes, building permits and, for developments, the trust structure."],
["Contract", "A promise of sale or purchase agreement setting out the price, payment schedule, delivery dates, penalties, guarantees and the condition that title is transferred free of liens."],
["Payment and signing", "Payment is made through traceable bank channels. Signatures are certified by a notary. If you are abroad, you can sign through an apostilled power of attorney."],
["Taxes", "The 3% transfer tax is assessed and paid at the tax authority (DGII), unless a CONFOTUR or other exemption applies."],
["Registration", "The file is lodged with the Title Registry, which issues a new Certificate of Title in your name. Only then is the purchase complete."],
],
"buy_box_title": "Off-plan purchases",
"buy_box": "If you buy into a project under construction, find out who the trustee is, which licenses the project holds, how your payments are released and what happens if the works are delayed. All of this should be written into the contract.",
"buy_time": "Indicative timeline: 30 to 90 days from signing to the issue of the new title, depending on the Title Registry involved and the complexity of the file.",

"cost_kicker": "04 · Costs",
"cost_title": "Purchase costs and taxes",
"cost_intro": "Beyond the price, you should budget for taxes and closing costs. The figures below are the general rates in force in 2026; every transaction must be calculated individually.",
"cost_rows": [
["Transfer tax", "3% of the higher of the contract price and the DGII appraisal. Paid by the buyer."],
["Real estate property tax (IPI)", "1% per year on the value above RD$10,695,494 (2026 threshold for individuals)."],
["Mortgage registration", "2% of the loan amount, when the purchase is financed with a mortgage."],
["Registry and notary fees", "Title Registry charges, signature certification and apostilles. They vary with the value and type of deed."],
["Legal fees", "Depending on the scope of work. At Cabinet Legal we quote a fixed fee before we start."],
],
"cost_after_title": "After the purchase",
"cost_after": [
["Rental income", "Rental income is subject to income tax. If the tenant is a company, a withholding may apply."],
["Future sale", "The gain on a sale is treated as a capital gain and taxed according to the seller's profile."],
["Retirees and rentiers", "Law 171-07 provides benefits such as a transfer tax exemption on the first home and IPI reductions, subject to requirements."],
],
"cost_note": "Rates and thresholds as published by the Dominican tax authority (DGII). They may be updated; always confirm before closing.",

"conf_kicker": "05 · Incentives",
"conf_title": "CONFOTUR: buying with tax exemptions",
"conf_intro": "Tourism Development Law 158-01, as amended by Law 195-13, attracts investment to tourist areas by granting tax exemptions to projects classified by the Tourism Promotion Council (CONFOTUR).",
"conf_band_l": "Years of tax benefits",
"conf_band_t": "From the completion of construction, the first buyer of a classified unit can enjoy exemptions that significantly reduce the total cost of owning the property.",
"conf_points": [
["Transfer tax exemption", "The first buyer of a unit in a classified project may be exempt from the 3% transfer tax."],
["IPI exemption", "While the benefit is in force, the property does not pay the annual real estate property tax."],
["15-year term", "Exemptions last 15 years from the completion of the project's construction and fit-out."],
],
"conf_warn_title": "What you should verify",
"conf_warn": [
"That the project holds a valid classification resolution and that your unit is included.",
"That you are the first buyer. Later resales do not automatically inherit the exemption.",
"That the developer has met the construction start deadlines required by law.",
"That the exemption is properly claimed and documented with the DGII at the time of transfer.",
],

"co_kicker": "06 · Companies",
"co_title": "Setting up a company",
"co_intro": "A foreigner can be the sole or majority owner of a Dominican company. The choice of corporate form determines the owners' liability, the flexibility to bring in investors and the cost of compliance.",
"co_types": [
["SRL", "Limited liability company", "The most common choice for small and mid-sized investments and for holding property. It requires at least two partners and is simple to manage."],
["SAS", "Simplified stock company", "Flexible internal organization, well suited to projects with several investors or funding rounds."],
["SA", "Stock corporation", "Designed for larger operations, with stricter capital and corporate governance requirements."],
["EIRL", "Individual limited liability company", "Lets an individual separate personal assets from the business without needing partners."],
],
"co_steps_title": "Usual process",
"co_steps": ["Trade name registration with ONAPI", "Drafting of bylaws and incorporation minutes", "Payment of incorporation tax at the DGII", "Registration with the Chamber of Commerce", "Tax ID (RNC) and tax registration", "Foreign investment registration with ProDominicana"],
"co_time": "Indicative timeline: three to six weeks, depending on the foreign partner's documents (apostilles and translations).",

"res_kicker": "07 · Residency",
"res_title": "Residency by investment",
"res_intro": "The General Directorate of Migration offers residency routes designed for investors and people with income from abroad. These are the ones our clients use most.",
"res_cards": [
["Investor", "US$200,000", "Minimum investment in the country, supported by the foreign investment registration certificate."],
["Rentier", "US$2,000 / month", "Stable income from a foreign source, backed by documents."],
["Retiree", "US$1,500 / month", "Pension from abroad, plus US$250 per month for each dependent."],
],
"res_points": [
"The application starts online on the Migration portal and is completed by lodging original documents in Santo Domingo.",
"The official processing time is around 45 business days once the file is complete.",
"Foreign documents must be apostilled and, where required, translated into Spanish.",
"Residency must be renewed on time; losing it through an oversight is one of the most common mistakes.",
],
"res_note": "Amounts as published by the General Directorate of Migration, September 2026.",

"err_kicker": "08 · Prevention",
"err_title": "Mistakes to avoid",
"errs": [
["Paying before checking the title", "A deposit or down payment made without a Title Registry search is the most frequent cause of losses."],
["Buying without a survey", "A property without an approved survey (deslinde) can lead to boundary disputes and make it harder to sell or finance."],
["Relying on generic contracts", "A contract without penalties, deadlines or guarantees leaves the buyer with no tools if the seller defaults."],
["Assuming CONFOTUR applies", "Not every unit in a tourism project is classified, and resales do not inherit the exemption."],
["Choosing the wrong structure", "Buying personally or through a company has different tax and estate consequences. Decide before you sign."],
["Using an agent without proper authority", "A power of attorney must set out precise powers and be apostilled and certified to be valid before notaries and registries."],
],
"check_title": "Checklist before you sign",
"checks": ["Recent original Certificate of Title and legal status certificate", "Seller's identity and legal capacity", "Approved survey and cadastral plan", "Property taxes and HOA fees up to date", "Project permits and trust agreement, if applicable", "Full calculation of taxes and closing costs"],

"us_kicker": "09 · About us",
"us_title": "Why Cabinet Legal",
"us_intro": "We are a Dominican firm with partners and an excellent team of lawyers organized by practice area. We work with foreign investors from the first consultation to the final registration.",
"us_stats": [["2009", "Year founded"], ["100%", "Remote by power of attorney"], ["12", "Practice areas"], ["3", "Languages: Spanish, English and French"]],
"us_points": [
["Direct partner attention", "Your matter is led by a partner, not an intermediary."],
["Remote transactions", "You can buy, incorporate or start your residency through a power of attorney, without travelling."],
["Technical verification", "We work with Land Consulting DR on the technical and registry review of every property."],
["Follow-through to the end", "We follow up with the DGII, Title Registry, ONAPI and Migration until each process is closed."],
],
"partners": [
["Aileen Espinosa", "Managing Partner", "Corporate law, business structuring, trademarks and intellectual property."],
["Ellis Beato", "Founding Partner", "Business law, litigation and dispute resolution."],
],

"cta_title": "Let's talk about your investment",
"cta_text": "Tell us what you plan to do in the Dominican Republic. A partner will review your case and explain the steps, timeline and cost before we begin.",
"cta_items": [["Web", "cabinetlegal.com.do/en/consulta"], ["WhatsApp", "+1 829 542 0615"], ["Email", "info@cabinetlegal.com.do"], ["Office", "Av. Pedro Henríquez Ureña No. 138, Torre Empresarial Reyna II, Suite 203, La Esperilla, Santo Domingo"]],
"cta_by_appt": "By appointment only",
"disclaimer": "This guide is for information purposes only and does not constitute legal advice on any specific matter. It reflects the laws and figures available in September 2026, which may change. Please consult a lawyer before making any decision. © 2026 Cabinet Legal.",
}
