C = {
"lang": "fr",
"file": "Guide-Investir-Republique-Dominicaine-2026-FR.pdf",
"cover_kicker": "Guide juridique pour investisseurs étrangers",
"cover_title": "Investir en République dominicaine",
"cover_year": "Édition 2026",
"cover_sub": "Ce qu'il faut savoir et vérifier avant d'investir, pour que votre patrimoine en République dominicaine soit protégé dès la première signature.",
"since": "Depuis 2009",
"footer": "Cabinet Legal · Guide pour investir en République dominicaine 2026",

"letter_kicker": "Lettre des associés",
"letter_title": "Un investissement sûr commence avant la signature",
"letter": [
"La République dominicaine vit la meilleure période de son histoire en tant que destination d'investissement. Chaque année, davantage d'acheteurs, d'entrepreneurs et de retraités y trouvent une combinaison rare : une croissance soutenue, une ouverture aux capitaux étrangers et une qualité de vie exceptionnelle.",
"L'expérience nous a aussi appris que les difficultés d'un investissement apparaissent rarement le jour de l'achat. Elles surgissent des années plus tard, lorsqu'un titre était grevé d'une charge que personne n'avait vérifiée, lorsqu'un projet n'avait pas tous ses permis ou lorsque la société avait été constituée selon une structure inadaptée aux projets de l'investisseur.",
"Nous avons préparé ce guide pour que vous abordiez chaque décision avec les bonnes informations. Il ne remplace pas un conseil adapté à votre situation, mais il vous aidera à poser les bonnes questions et à repérer à temps les signaux d'alerte.",
],
"sign": "Aileen Espinosa et Ellis Beato",
"sign_role": "Associés, Cabinet Legal",
"toc_title": "Sommaire",
"toc": ["Pourquoi la République dominicaine", "Cadre juridique de l'investisseur étranger", "Acheter un bien étape par étape", "Coûts et impôts de l'achat", "Incitations CONFOTUR", "Créer une société", "Résidence par investissement", "Erreurs à éviter", "Pourquoi Cabinet Legal"],

"why_kicker": "01 · Contexte",
"why_title": "Pourquoi la République dominicaine",
"why_intro": "L'économie dominicaine figure parmi les plus dynamiques d'Amérique latine depuis deux décennies. En 2025, le pays a battu des records d'investissement étranger et de tourisme, les deux moteurs de la demande immobilière.",
"stats": [
["5,03 Md US$", "d'investissement direct étranger en 2025, le plus haut niveau de son histoire"],
["+11,3 %", "de croissance de l'investissement étranger par rapport à 2024"],
["11,68 M", "de visiteurs en 2025, également un record historique"],
["15,7 %", "de l'investissement étranger de 2025 est allé à l'immobilier"],
],
"stats_source": "Sources : Banque centrale de la République dominicaine (IDE 2025) et ministère du Tourisme (arrivées 2025).",
"why_points_title": "Avantages pour l'investisseur",
"why_points": [
["Égalité de traitement", "La loi 16-95 reconnaît à l'investisseur étranger les mêmes droits qu'au national et garantit le libre rapatriement des capitaux et des bénéfices."],
["Propriété sans restriction", "Un étranger peut acheter un bien à son nom ou par l'intermédiaire d'une société, sans condition de résidence ni associé dominicain."],
["Titres enregistrés", "Le système de la loi 108-05 sur le Registre immobilier garantit la propriété par un Certificat de titre délivré par l'État."],
["Incitations fiscales", "Les projets touristiques classés CONFOTUR offrent des exonérations qui peuvent améliorer nettement la rentabilité."],
],
"sectors_title": "Destination de l'investissement étranger en 2025",
"sectors": [["Tourisme", 26.3], ["Énergie", 23.8], ["Immobilier", 15.7], ["Commerce et industrie", 10.5], ["Zones franches", 8.7], ["Mines", 6.7], ["Autres", 8.3]],

"legal_kicker": "02 · Cadre juridique",
"legal_title": "Les lois qui protègent votre investissement",
"legal_intro": "Connaître le cadre juridique permet de savoir quels droits vous avez, quelles obligations vous assumez et quels documents exiger à chaque opération.",
"laws": [
["Loi 16-95", "Investissement étranger", "Garantit l'égalité de traitement et le libre transfert des capitaux et bénéfices. L'enregistrement de l'investissement auprès de ProDominicana permet de demander la résidence d'investisseur."],
["Loi 108-05", "Registre immobilier", "Encadre le Certificat de titre, le bornage (deslinde) et l'inscription des droits. Ce qui n'est pas inscrit au Registre des titres n'est pas opposable aux tiers."],
["Loi 479-08", "Sociétés commerciales", "Définit les formes de société (SRL, SA, SAS, EIRL), leurs exigences de capital, leurs organes de gestion et leurs obligations d'enregistrement."],
["Loi 189-11", "Marché hypothécaire et fiducie", "Permet d'acheter sur plan au moyen de fiducies qui séparent les fonds des acheteurs du patrimoine du promoteur."],
["Loi 158-01", "Développement touristique (CONFOTUR)", "Modifiée par la loi 195-13. Accorde des exonérations fiscales aux projets touristiques classés et à leurs premiers acquéreurs."],
["Loi 171-07", "Rentiers et retraités", "Accorde des avantages migratoires et fiscaux aux étrangers justifiant de revenus ou de pensions stables de l'étranger."],
],
"legal_note": "Un avertissement pratique : en République dominicaine, la possession physique d'un bien ne remplace jamais le titre. Vérifiez toujours la situation juridique au Registre des titres avant de payer.",

"buy_kicker": "03 · Achat immobilier",
"buy_title": "Acheter un bien étape par étape",
"buy_intro": "Le processus est sûr lorsque chaque étape est exécutée dans le bon ordre et avec un dossier complet. Voici les étapes d'un achat bien structuré.",
"steps": [
["Offre et réservation", "Le prix est convenu et un accord de réservation est signé. Avant tout versement, vérifiez qui est le propriétaire inscrit et à quelles conditions la réservation est remboursée."],
["Vérifications préalables", "Examen du Certificat de titre, certificat de situation juridique, charges et hypothèques, bornage et plan cadastral, impôts à jour, permis de construire et, pour un projet, structure de la fiducie."],
["Contrat", "Promesse ou contrat de vente précisant le prix, les modalités de paiement, les délais de livraison, les pénalités, les garanties et le transfert du titre libre de toute charge."],
["Paiement et signature", "Le paiement passe par des canaux bancaires traçables. Les signatures sont légalisées par un notaire. Depuis l'étranger, vous pouvez signer par procuration apostillée."],
["Impôts", "L'impôt de transfert de 3 % est liquidé et payé auprès de l'administration fiscale (DGII), sauf exonération CONFOTUR ou autre."],
["Inscription", "Le dossier est déposé au Registre des titres, qui délivre un nouveau Certificat de titre à votre nom. L'achat n'est complet qu'à ce moment-là."],
],
"buy_box_title": "Achats sur plan",
"buy_box": "Pour un projet en construction, demandez qui est le fiduciaire, quelles licences détient le projet, comment vos paiements sont débloqués et ce qui se passe en cas de retard. Tout cela doit figurer par écrit dans le contrat.",
"buy_time": "Délai indicatif : de 30 à 90 jours entre la signature et la délivrance du nouveau titre, selon le Registre des titres concerné et la complexité du dossier.",

"cost_kicker": "04 · Coûts",
"cost_title": "Coûts et impôts de l'achat",
"cost_intro": "Au-delà du prix, il faut prévoir les impôts et les frais de clôture. Les chiffres ci-dessous sont les taux généraux en vigueur en 2026 ; chaque opération doit être calculée individuellement.",
"cost_rows": [
["Impôt de transfert", "3 % de la valeur la plus élevée entre le prix du contrat et l'évaluation de la DGII. À la charge de l'acheteur."],
["Impôt sur le patrimoine immobilier (IPI)", "1 % par an sur la valeur dépassant 10 695 494 RD$ (seuil 2026 pour les personnes physiques)."],
["Inscription d'hypothèque", "2 % du montant du prêt, lorsque l'achat est financé par un crédit hypothécaire."],
["Frais de registre et de notaire", "Droits du Registre des titres, légalisation des signatures et apostilles. Ils varient selon la valeur et le type d'acte."],
["Honoraires juridiques", "Selon l'étendue de la mission. Chez Cabinet Legal, nous proposons un forfait avant de commencer."],
],
"cost_after_title": "Après l'achat",
"cost_after": [
["Revenus locatifs", "Les loyers sont soumis à l'impôt sur le revenu. Si le locataire est une société, une retenue peut s'appliquer."],
["Revente", "La plus-value réalisée est traitée comme un gain en capital et imposée selon le profil du vendeur."],
["Retraités et rentiers", "La loi 171-07 prévoit des avantages, comme l'exonération de l'impôt de transfert sur la première résidence et des réductions d'IPI, sous conditions."],
],
"cost_note": "Taux et seuils publiés par l'administration fiscale dominicaine (DGII). Ils peuvent évoluer ; vérifiez toujours avant la clôture.",

"conf_kicker": "05 · Incitations",
"conf_title": "CONFOTUR : acheter avec des exonérations fiscales",
"conf_intro": "La loi 158-01 sur le développement touristique, modifiée par la loi 195-13, attire l'investissement dans les zones touristiques grâce à des exonérations accordées aux projets classés par le Conseil de promotion touristique (CONFOTUR).",
"conf_band_l": "Années d'avantages fiscaux",
"conf_band_t": "À compter de l'achèvement des travaux, le premier acquéreur d'une unité classée peut bénéficier d'exonérations qui réduisent sensiblement le coût total de détention du bien.",
"conf_points": [
["Exonération de l'impôt de transfert", "Le premier acquéreur d'une unité dans un projet classé peut être exonéré des 3 %."],
["Exonération de l'IPI", "Pendant la durée de l'avantage, le bien ne paie pas l'impôt annuel sur le patrimoine immobilier."],
["Durée de 15 ans", "Les exonérations courent 15 ans à compter de l'achèvement de la construction et de l'équipement du projet."],
],
"conf_warn_title": "Ce qu'il faut vérifier",
"conf_warn": [
"Que le projet dispose d'une résolution de classement en vigueur et que votre unité y figure.",
"Que vous êtes le premier acquéreur. Les reventes ultérieures n'héritent pas automatiquement de l'exonération.",
"Que le promoteur a respecté les délais de démarrage des travaux exigés par la loi.",
"Que l'exonération est correctement demandée et documentée auprès de la DGII lors du transfert.",
],

"co_kicker": "06 · Sociétés",
"co_title": "Créer une société",
"co_intro": "Un étranger peut être associé unique ou majoritaire d'une société dominicaine. Le choix de la forme sociale détermine la responsabilité des associés, la souplesse pour accueillir des investisseurs et le coût de conformité.",
"co_types": [
["SRL", "Société à responsabilité limitée", "La plus utilisée pour les investissements petits et moyens et pour détenir un bien. Elle exige au moins deux associés et se gère simplement."],
["SAS", "Société par actions simplifiée", "Organisation interne souple, adaptée aux projets réunissant plusieurs investisseurs ou des levées de fonds."],
["SA", "Société anonyme", "Conçue pour des opérations de plus grande envergure, avec des exigences de capital et de gouvernance plus strictes."],
["EIRL", "Entreprise individuelle à responsabilité limitée", "Permet à une personne physique de séparer son patrimoine personnel de l'activité sans avoir d'associés."],
],
"co_steps_title": "Démarche habituelle",
"co_steps": ["Enregistrement du nom commercial à l'ONAPI", "Rédaction des statuts et procès-verbaux constitutifs", "Paiement de l'impôt de constitution à la DGII", "Inscription au Registre du commerce", "Obtention du RNC et immatriculation fiscale", "Enregistrement de l'investissement étranger à ProDominicana"],
"co_time": "Délai indicatif : trois à six semaines, selon les documents de l'associé étranger (apostilles et traductions).",

"res_kicker": "07 · Résidence",
"res_title": "Résidence par investissement",
"res_intro": "La Direction générale des migrations propose des voies de résidence pour les investisseurs et les personnes disposant de revenus de l'étranger. Voici celles que nos clients utilisent le plus.",
"res_cards": [
["Investisseur", "200 000 US$", "Investissement minimum dans le pays, justifié par le certificat d'enregistrement de l'investissement étranger."],
["Rentier", "2 000 US$ / mois", "Revenus stables de source étrangère, justifiés par des documents."],
["Retraité", "1 500 US$ / mois", "Pension de l'étranger, plus 250 US$ par mois pour chaque personne à charge."],
],
"res_points": [
"La demande débute en ligne sur le portail des Migrations et se termine par le dépôt des originaux à Saint-Domingue.",
"Le délai officiel de traitement est d'environ 45 jours ouvrables une fois le dossier complet.",
"Les documents étrangers doivent être apostillés et, si nécessaire, traduits en espagnol.",
"La résidence doit être renouvelée dans les délais ; la perdre par simple oubli est l'une des erreurs les plus fréquentes.",
],
"res_note": "Montants publiés par la Direction générale des migrations, septembre 2026.",

"err_kicker": "08 · Prévention",
"err_title": "Erreurs à éviter",
"errs": [
["Payer avant de vérifier le titre", "Une réservation ou un acompte versé sans consultation du Registre des titres est la première cause de pertes."],
["Acheter sans bornage", "Un bien sans bornage (deslinde) approuvé peut entraîner des litiges de limites et compliquer sa vente ou son financement."],
["Se fier à des contrats types", "Un contrat sans pénalités, délais ni garanties laisse l'acheteur démuni si le vendeur ne respecte pas ses engagements."],
["Supposer que CONFOTUR s'applique", "Toutes les unités d'un projet touristique ne sont pas classées, et les reventes n'héritent pas de l'exonération."],
["Choisir la mauvaise structure", "Acheter en nom propre ou par une société a des effets fiscaux et successoraux différents. Décidez-le avant de signer."],
["Mandater sans pouvoir adéquat", "La procuration doit préciser les pouvoirs, être apostillée et légalisée pour être valable devant notaire et registres."],
],
"check_title": "Liste de contrôle avant de signer",
"checks": ["Certificat de titre original et certificat de situation juridique récents", "Identité et capacité juridique du vendeur", "Bornage approuvé et plan cadastral", "Impôts et charges de copropriété à jour", "Permis du projet et contrat de fiducie, le cas échéant", "Calcul complet des impôts et frais de clôture"],

"us_kicker": "09 · Qui sommes-nous",
"us_title": "Pourquoi Cabinet Legal",
"us_intro": "Nous sommes un cabinet dominicain composé d'associés et d'une excellente équipe d'avocats organisée par domaine d'expertise. Nous accompagnons les investisseurs étrangers de la première consultation jusqu'à l'inscription finale.",
"us_stats": [["2009", "Année de fondation"], ["100%", "Démarches par procuration"], ["12", "Domaines d'expertise"], ["3", "Langues : espagnol, anglais et français"]],
"us_points": [
["Suivi direct par un associé", "Votre dossier est dirigé par un associé, pas par un intermédiaire."],
["Démarches à distance", "Vous pouvez acheter, créer votre société ou lancer votre résidence par procuration, sans vous déplacer."],
["Vérification technique", "Nous travaillons avec Land Consulting DR pour l'examen technique et registral de chaque bien."],
["Suivi jusqu'au bout", "Nous assurons le suivi auprès de la DGII, du Registre des titres, de l'ONAPI et des Migrations jusqu'à la clôture."],
],
"partners": [
["Aileen Espinosa", "Associée gérante", "Droit des sociétés, structuration d'entreprises, marques et propriété intellectuelle."],
["Ellis Beato", "Associé fondateur", "Droit des affaires, contentieux et règlement des différends."],
],

"cta_title": "Parlons de votre investissement",
"cta_text": "Dites-nous ce que vous envisagez en République dominicaine. Un associé examinera votre dossier et vous indiquera les étapes, les délais et le coût avant de commencer.",
"cta_items": [["Web", "cabinetlegal.com.do/fr/consulta"], ["WhatsApp", "+1 829 542 0615"], ["Courriel", "info@cabinetlegal.com.do"], ["Bureau", "Av. Pedro Henríquez Ureña No. 138, Torre Empresarial Reyna II, Suite 203, La Esperilla, Saint-Domingue"]],
"cta_by_appt": "Sur rendez-vous uniquement",
"disclaimer": "Ce guide est fourni à titre purement informatif et ne constitue pas un conseil juridique sur un cas particulier. Il reflète la réglementation et les chiffres disponibles en septembre 2026, susceptibles d'évoluer. Consultez un avocat avant toute décision. © 2026 Cabinet Legal.",
}
