C = {
"lang": "es",
"file": "Guia-Invertir-Republica-Dominicana-2026-ES.pdf",
"cover_kicker": "Guía legal para inversionistas extranjeros",
"cover_title": "Invertir en República Dominicana",
"cover_year": "Edición 2026",
"cover_sub": "Lo que debe saber y verificar antes de invertir, para que su patrimonio en República Dominicana quede protegido desde la primera firma.",
"since": "Desde 2009",
"footer": "Cabinet Legal · Guía para invertir en República Dominicana 2026",

"letter_kicker": "Carta de los socios",
"letter_title": "Una inversión segura empieza antes de firmar",
"letter": [
"República Dominicana vive el mejor momento de su historia como destino de inversión. Cada año llegan más compradores, emprendedores y jubilados que ven en el país una combinación difícil de encontrar: crecimiento sostenido, apertura al capital extranjero y una calidad de vida excepcional.",
"También sabemos, por experiencia, que los problemas de una inversión casi nunca aparecen el día de la compra. Aparecen años después, cuando un título tenía una carga que nadie revisó, cuando un proyecto no tenía los permisos completos o cuando la sociedad se constituyó con una estructura que no respondía a los planes del inversionista.",
"Preparamos esta guía para que usted llegue a cada decisión con la información correcta. No sustituye la asesoría sobre su caso concreto, pero le permitirá hacer las preguntas adecuadas y reconocer a tiempo las señales de alerta.",
],
"sign": "Aileen Espinosa y Ellis Beato",
"sign_role": "Socios de Cabinet Legal",
"toc_title": "Contenido",
"toc": ["Por qué República Dominicana", "Marco legal del inversionista extranjero", "Comprar un inmueble paso a paso", "Costos e impuestos de la compra", "Incentivos CONFOTUR", "Constituir una empresa", "Residencia por inversión", "Errores que debe evitar", "Por qué Cabinet Legal"],

"why_kicker": "01 · Contexto",
"why_title": "Por qué República Dominicana",
"why_intro": "La economía dominicana ha sido una de las de mayor crecimiento de América Latina durante las últimas dos décadas. En 2025 el país alcanzó cifras récord tanto en inversión extranjera como en turismo, los dos motores que sostienen la demanda inmobiliaria.",
"stats": [
["US$5,032 MM", "de inversión extranjera directa en 2025, la cifra más alta de su historia"],
["+11.3 %", "de crecimiento de la inversión extranjera frente a 2024"],
["11.68 MM", "de visitantes en 2025, también un récord histórico"],
["15.7 %", "de la inversión extranjera de 2025 se destinó al sector inmobiliario"],
],
"stats_source": "Fuentes: Banco Central de la República Dominicana (IED 2025) y Ministerio de Turismo (llegadas 2025).",
"why_points_title": "Ventajas para el inversionista",
"why_points": [
["Igualdad de trato", "La Ley 16-95 reconoce al inversionista extranjero los mismos derechos que al nacional y garantiza la libre repatriación de capitales y utilidades."],
["Propiedad sin restricciones", "Un extranjero puede comprar inmuebles a su nombre o a través de una sociedad, sin necesidad de residencia ni de socio dominicano."],
["Títulos registrados", "El sistema de la Ley 108-05 de Registro Inmobiliario respalda la propiedad con un Certificado de Título emitido por el Estado."],
["Incentivos fiscales", "Los proyectos turísticos clasificados bajo CONFOTUR ofrecen exenciones que pueden hacer más rentable la inversión."],
],
"sectors_title": "Destino de la inversión extranjera en 2025",
"sectors": [["Turismo", 26.3], ["Energía", 23.8], ["Inmobiliario", 15.7], ["Comercio e industria", 10.5], ["Zonas francas", 8.7], ["Minería", 6.7], ["Otros", 8.3]],

"legal_kicker": "02 · Marco legal",
"legal_title": "Las normas que protegen su inversión",
"legal_intro": "Conocer el marco jurídico le permite entender qué derechos tiene, qué obligaciones asume y qué documentos debe exigir en cada operación.",
"laws": [
["Ley 16-95", "Inversión extranjera", "Garantiza igualdad de trato y la libre remesa de capital y beneficios. El registro de la inversión ante ProDominicana es la base para solicitar la residencia como inversionista."],
["Ley 108-05", "Registro Inmobiliario", "Regula el Certificado de Título, los deslindes y la inscripción de derechos. Lo que no está inscrito en el Registro de Títulos no es oponible a terceros."],
["Ley 479-08", "Sociedades comerciales", "Establece las formas societarias (SRL, SA, SAS, EIRL), sus requisitos de capital, órganos de gestión y obligaciones de registro."],
["Ley 189-11", "Mercado hipotecario y fideicomiso", "Permite comprar proyectos en planos a través de fideicomisos que separan los fondos del patrimonio del desarrollador."],
["Ley 158-01", "Fomento turístico (CONFOTUR)", "Modificada por la Ley 195-13. Otorga exenciones fiscales a proyectos turísticos clasificados y a sus primeros adquirientes."],
["Ley 171-07", "Rentistas y pensionados", "Concede beneficios migratorios y fiscales a extranjeros que demuestran ingresos o pensiones estables del exterior."],
],
"legal_note": "Una advertencia práctica: en República Dominicana la posesión física de un inmueble no sustituye el título. Siempre verifique el estado jurídico en el Registro de Títulos antes de pagar.",

"buy_kicker": "03 · Compra de inmuebles",
"buy_title": "Comprar un inmueble paso a paso",
"buy_intro": "El proceso es seguro cuando cada paso se ejecuta en el orden correcto y con la documentación completa. Estas son las etapas de una compra bien estructurada.",
"steps": [
["Oferta y reserva", "Se acuerda el precio y se firma un acuerdo de reserva. Antes de entregar dinero, confirme quién es el propietario registrado y bajo qué condiciones se devuelve la reserva."],
["Debida diligencia", "Revisión del Certificado de Título, certificación de estado jurídico, cargas y gravámenes, deslinde y plano catastral, impuestos al día, permisos de construcción y, en proyectos, la estructura del fideicomiso."],
["Contrato", "Promesa de venta o contrato de compraventa con precio, forma de pago, plazos de entrega, penalidades, garantías y la condición de que el título se transfiera libre de cargas."],
["Pago y firma", "El pago se canaliza por vías bancarias trazables. Las firmas se legalizan ante notario. Si usted no está en el país, puede firmar mediante poder apostillado."],
["Impuestos", "Se liquida y paga en la DGII el impuesto de transferencia del 3 % (salvo exención CONFOTUR u otra aplicable)."],
["Registro", "Se deposita el expediente en el Registro de Títulos, que emite un nuevo Certificado de Título a su nombre. Solo entonces la compra está completa."],
],
"buy_box_title": "Compras en planos",
"buy_box": "Si compra un proyecto en construcción, exija conocer quién es el fiduciario, qué licencias tiene el proyecto, cómo se desembolsan sus pagos y qué ocurre si la obra se retrasa. Estos puntos deben quedar por escrito en el contrato.",
"buy_time": "Plazo orientativo: entre 30 y 90 días desde la firma hasta la emisión del nuevo título, según el Registro de Títulos correspondiente y la complejidad del expediente.",

"cost_kicker": "04 · Costos",
"cost_title": "Costos e impuestos de la compra",
"cost_intro": "Además del precio, conviene presupuestar los impuestos y gastos de cierre. Las cifras siguientes son las generales vigentes en 2026; cada operación debe calcularse de forma individual.",
"cost_rows": [
["Impuesto de transferencia", "3 % del mayor valor entre el precio del contrato y la tasación de la DGII. Lo paga el comprador."],
["Impuesto al Patrimonio Inmobiliario (IPI)", "1 % anual sobre el valor que exceda RD$10,695,494 (umbral 2026 para personas físicas)."],
["Registro de hipoteca", "2 % del monto del préstamo, cuando la compra se financia con garantía hipotecaria."],
["Tasas registrales y notariales", "Cargos del Registro de Títulos, legalización de firmas y apostillas. Varían según el valor y el tipo de acto."],
["Honorarios legales", "Según el alcance del servicio. En Cabinet Legal ofrecemos una cotización fija antes de iniciar."],
],
"cost_after_title": "Después de la compra",
"cost_after": [
["Alquileres", "Los ingresos por alquiler están gravados con el Impuesto sobre la Renta. Si el inquilino es una empresa, puede aplicar una retención."],
["Venta futura", "La ganancia obtenida al vender se considera ganancia de capital y tributa según el perfil del vendedor."],
["Pensionados y rentistas", "La Ley 171-07 prevé beneficios, como la exención del impuesto de transferencia en la primera vivienda y reducciones del IPI, sujetos a requisitos."],
],
"cost_note": "Tasas y umbrales según la Dirección General de Impuestos Internos (DGII). Pueden actualizarse; confirme siempre antes del cierre.",

"conf_kicker": "05 · Incentivos",
"conf_title": "CONFOTUR: comprar con exenciones fiscales",
"conf_intro": "La Ley 158-01 de Fomento al Desarrollo Turístico, modificada por la Ley 195-13, busca atraer inversión a zonas turísticas mediante exenciones fiscales para proyectos clasificados por el Consejo de Fomento Turístico (CONFOTUR).",
"conf_points": [
["Exención del impuesto de transferencia", "El primer comprador de una unidad en un proyecto clasificado puede quedar exento del 3 %."],
["Exención del IPI", "Durante el período de vigencia del beneficio, el inmueble no paga el impuesto anual al patrimonio inmobiliario."],
["Plazo de 15 años", "Las exenciones se extienden por 15 años contados desde la terminación de la construcción y equipamiento del proyecto."],
],
"conf_warn_title": "Lo que debe verificar",
"conf_warn": [
"Que el proyecto tenga una resolución de clasificación vigente y que su unidad esté incluida.",
"Que usted sea el primer adquiriente. Las reventas posteriores no heredan automáticamente la exención.",
"Que el desarrollador haya cumplido los plazos de inicio de obra exigidos por la ley.",
"Que la exención se solicite y se documente correctamente ante la DGII al momento de la transferencia.",
],

"co_kicker": "06 · Empresas",
"co_title": "Constituir una empresa",
"co_intro": "Un extranjero puede ser socio único o mayoritario de una sociedad dominicana. La elección de la forma societaria define la responsabilidad de los socios, la flexibilidad para admitir inversionistas y el costo de cumplimiento.",
"co_types": [
["SRL", "Sociedad de Responsabilidad Limitada", "La más utilizada por pequeñas y medianas inversiones y para tener inmuebles. Requiere al menos dos socios y ofrece una administración sencilla."],
["SAS", "Sociedad Anónima Simplificada", "Flexible en su organización interna, adecuada para proyectos con varios inversionistas o rondas de capital."],
["SA", "Sociedad Anónima", "Pensada para operaciones de mayor escala, con requisitos de capital y de gobierno corporativo más exigentes."],
["EIRL", "Empresa Individual de Responsabilidad Limitada", "Permite a una persona física separar su patrimonio personal del negocio sin necesidad de socios."],
],
"co_steps_title": "Proceso habitual",
"co_steps": ["Registro del nombre comercial en ONAPI", "Redacción de estatutos y actas constitutivas", "Pago del impuesto de constitución en la DGII", "Inscripción en el Registro Mercantil de la Cámara de Comercio", "Obtención del RNC y alta fiscal", "Registro de la inversión extranjera en ProDominicana"],
"co_time": "Plazo orientativo: de tres a seis semanas, según la documentación del socio extranjero (apostillas y traducciones).",

"res_kicker": "07 · Residencia",
"res_title": "Residencia por inversión",
"res_intro": "La Dirección General de Migración ofrece vías de residencia pensadas para inversionistas y personas con ingresos del exterior. Estas son las más utilizadas por nuestros clientes.",
"res_cards": [
["Inversionista", "US$200,000", "Inversión mínima en el país, respaldada por el certificado de registro de inversión extranjera."],
["Rentista", "US$2,000 al mes", "Ingresos estables de fuente extranjera, demostrados documentalmente."],
["Pensionado", "US$1,500 al mes", "Pensión del exterior, más US$250 mensuales por cada dependiente."],
],
"res_points": [
"El trámite se inicia en línea en el portal de la Dirección General de Migración y se completa con el depósito de documentos originales en Santo Domingo.",
"El plazo oficial de respuesta ronda los 45 días laborables una vez completo el expediente.",
"Los documentos extranjeros deben estar apostillados y, cuando corresponda, traducidos al español.",
"La residencia debe renovarse en los plazos establecidos; perderla por descuido es uno de los errores más comunes.",
],
"res_note": "Montos según la Dirección General de Migración, septiembre de 2026.",

"err_kicker": "08 · Prevención",
"err_title": "Errores que debe evitar",
"errs": [
["Pagar antes de verificar el título", "Una reserva o un pago inicial sin revisión del Registro de Títulos es el origen más frecuente de pérdidas."],
["Comprar sin deslinde", "Un inmueble sin deslinde aprobado puede generar conflictos sobre sus linderos y dificultar su venta o financiamiento."],
["Confiar en contratos genéricos", "Un contrato sin penalidades, plazos ni garantías deja al comprador sin herramientas si el vendedor incumple."],
["Suponer que existe la exención CONFOTUR", "No todas las unidades de un proyecto turístico están clasificadas, y las reventas no la heredan."],
["Elegir mal la estructura", "Comprar a título personal o por sociedad tiene efectos fiscales y sucesorales distintos. Conviene decidirlo antes de firmar."],
["Usar un representante sin poder adecuado", "El poder debe tener facultades precisas, estar apostillado y legalizado para ser válido ante notario y registros."],
],
"check_title": "Lista de control antes de firmar",
"checks": ["Certificado de Título original y certificación de estado jurídico recientes", "Identidad y capacidad legal del vendedor", "Deslinde aprobado y plano catastral", "Impuestos y cuotas de mantenimiento al día", "Permisos del proyecto y contrato de fideicomiso, si aplica", "Cálculo total de impuestos y gastos de cierre"],

"us_kicker": "09 · Nosotros",
"us_title": "Por qué Cabinet Legal",
"us_intro": "Somos una firma dominicana con socios y un excelente equipo de abogados organizado por áreas de práctica. Acompañamos a inversionistas extranjeros desde la primera consulta hasta el registro final.",
"us_stats": [["2009", "Año de fundación"], ["100%", "Trámites por poder, sin viajar"], ["12", "Áreas de práctica"], ["3", "Idiomas: español, inglés y francés"]],
"us_points": [
["Atención directa de socios", "Su caso lo dirige un socio, no un intermediario."],
["Trámites a distancia", "Puede comprar, constituir su empresa o iniciar su residencia mediante poder, sin viajar al país."],
["Verificación técnica", "Trabajamos junto a Land Consulting DR para la revisión técnica y registral de cada propiedad."],
["Seguimiento hasta el final", "Damos seguimiento ante la DGII, el Registro de Títulos, ONAPI y Migración hasta que el trámite concluye."],
],
"partners": [
["Aileen Espinosa", "Socia gerente", "Derecho corporativo, estructuración de negocios, marcas y propiedad intelectual."],
["Ellis Beato", "Socio fundador", "Negocios, litigación y resolución de conflictos."],
],

"cta_title": "Hablemos de su inversión",
"cta_text": "Cuéntenos qué planea hacer en República Dominicana. Un socio revisará su caso y le indicará los pasos, los plazos y el costo antes de comenzar.",
"cta_items": [["Web", "cabinetlegal.com.do/consulta"], ["WhatsApp", "+1 829 542 0615"], ["Correo", "info@cabinetlegal.com.do"], ["Oficina", "Av. Pedro Henríquez Ureña No. 138, Torre Empresarial Reyna II, Suite 203, La Esperilla, Santo Domingo"]],
"cta_by_appt": "Atención con cita previa",
"disclaimer": "Esta guía tiene fines exclusivamente informativos y no constituye asesoría legal para un caso concreto. La información refleja la normativa y las cifras disponibles en septiembre de 2026 y puede variar. Antes de tomar cualquier decisión, consulte a un abogado. © 2026 Cabinet Legal.",
}
C["conf_band_l"] = "Años de beneficios fiscales"
C["conf_band_t"] = "Desde la terminación de la obra, el primer adquiriente de una unidad clasificada puede disfrutar de exenciones que reducen de forma significativa el costo total de tener el inmueble."
